apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cnat-user-service-skaffold
build:
  artifacts:
    - image: cnat-user-service
      context: ./
    - image: cnat-user-service-test
      context: ./
      custom:
        buildCommand: docker build --target test
test:
  - image: cnat-user-service-test
    custom:
      - command: docker run --rm $IMAGE
deploy:
  kubectl:
    manifests:
      - k8s/k8s-cnat-user-service.yaml
