apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cnat-user-service-skaffold
build:
  artifacts:
    - image: cnat-user-service
      context: ./
deploy:
  kubectl:
    manifests:
      - k8s/k8s-cnat-user-service.yaml
