apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cnat-user-service-skaffold
build:
  artifacts:
    - image: cnat-user-service
      context: ./
    - image: cnat-user-service-test
      context: ./
      docker:
        buildArgs:
          --target: test
test:
  - image: cnat-user-service-test
    custom:
      - command: echo $IMAGE && docker run --rm $IMAGE
deploy:
  kubectl:
    manifests:
      - k8s/k8s-cnat-user-service.yaml
