server:
  port: 80
  error:
    include-message: always

spring:
  #  sql:
  #    init:
  #      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${CNAT_USER_SERVICE_POSTGRES_URI}
    username: ${CNAT_USER_SERVICE_POSTGRES_USERNAME}
    password: ${CNAT_USER_SERVICE_POSTGRES_PASSWORD}

management:
  endpoint:
    health:
      #show-details: always
      probes:
        enabled: true
