server:
  port: 8082

spring:
  #  sql:
  #    init:
  #      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: #jdbc:postgresql://host:5432/cnat-user-service-db
    username: #username
    password: #password
